# Generated by Django 2.2.12 on 2021-12-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='texarea',
            new_name='desc',
        ),
    ]
